# Generated by Django 2.2.6 on 2019-11-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='register',
            name='new_password',
        ),
    ]
